# Generated by Django 3.2.16 on 2024-07-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='group_id',
            new_name='group',
        ),
    ]
